### ISSUE TITLE
Unable to decompress pdfs made by ./bro -q 2

### ISSUE THREAD

**Issue by danielrh** [ende76/brotli-rs#16]
Hi--
I tried running the rust brotli decompressor--and if I use -q 2 on the encoding for big binary files, it fails to decode

here's an example
https://www.dropbox.com/s/nzvkt9pl94qb3b8/origin.br?dl=0
https://www.dropbox.com/s/m35k1udfe56b1wp/origin.pdf?dl=0

Any idea what the issue is? The output is only 128KB and doesn't match the original

**Comment by ende76** [comment]
Your fix solves the issue. Thanks!
