### ISSUE TITLE
zip file compressed with brotli doesn't roundtrip

### ISSUE THREAD

**Issue by danielrh** [ende76/brotli-rs#21]
https://www.dropbox.com/s/ubfjbfe0oowfvtl/svg.zip?dl=0
when compressed to brotli is
https://www.dropbox.com/s/9ifkxzaxblfhz50/svg.zip.compressed?dl=0

and it fails to roundtrip with the following message
```
"data/svg.zip.compressed":
output length = 65703
res = Err(Error { repr: Custom(Custom { kind: InvalidData, error: StringError("More uncompressed bytes than expected in meta-block") }) })
===========
```

However the copy and insert lengths appear to be the same as with the google-provided decompressor
https://www.dropbox.com/s/gc6rjqtca4mi4cx/svg.zip.cerrlog.txt?dl=0

brotli's log:

https://www.dropbox.com/s/vptya6rxmks5f97/svg.zip.errlog.txt?dl=0

Here's the tail end of the log from the brotli-rs binary

```
Insert And Copy Length = 137
(m_len, self.meta_block.count_output, insert_length, copy_length) = (87897, 87883, 1, 3)
btype = 0
[p1, p2] = RingBuffer { buf: [0, 0], pos: 0, cap: 2 }
Context Mode = 3
Lit = 0 0
Count output 87884
Count output 87887
Insert And Copy Length = 182
(m_len, self.meta_block.count_output, insert_length, copy_length) = (87897, 87887, 6, 8)
Fatal (m_len, a, b, c) = (87897, 87887, 87893, 87901)
output length = 65703
res = Err(Error { repr: Custom(Custom { kind: InvalidData, error: StringError("More uncompressed bytes than expected in meta-block") }) })
===========

OK ()
```

**Comment by danielrh** [comment]
if I sum up the sizes from the google decompression, they don't exactly add up to 87897 either
...
Copy 4 Insert 4
Copy 3 Insert 1
Copy 8 Insert 6
Total Copy = 33781
Total Insert = 54139
Total = 87920

This doesn't seem to add up to 87897 even if you take out the last copy length

**Comment by danielrh** [comment]
it seems like a close reading of the spec indicates that the insertion length can also exceed the metablock size:

```
loop for ILEN
               if BLEN_L is zero
                  read block type using HTREE_BTYPE_L and set BTYPE_L
                     save previous block type
                  read block count using HTREE_BLEN_L and set BLEN_L
               decrement BLEN_L
               look up context mode CMODE[BTYPE_L]
               compute context ID, CIDL from last two uncompressed bytes
               read literal using HTREEL[CMAPL[64*BTYPE_L + CIDL]]
               write literal to uncompressed stream
            if number of uncompressed bytes produced in the loop for
               this meta-block is MLEN, then break from loop (in this
               case the copy length is ignored and can have any value)
```

**Comment by danielrh** [comment]
It appears the decoder google wrote does, indeed, require that the *copy length* never overruns the metablock size...so really only the insertion length can overshoot, as far as it seems.

**Comment by danielrh** [comment]
Aha in this case the last item was a transformed dictionary word transformed from len 8 to 4, probably using the kOmit* transforms

**Comment by ende76** [comment]
@danielrh  Riveting investigation! I only just saw this.
If I understand your findings so far, it looks like brotli-rs _believes_ one metablock to be overshooting its allotted output size by 4 bytes, but you've found that due the a transformation, those 4 bytes actually get deleted again?
In that case, it would seem that the check for m_len vs. metablock.count_output needs to be moved to after possible transformations have been applied.
Possibly taking into account the case when there is no transformation.

**Comment by danielrh** [comment]
That is correct.

There is another bug as well (where insert length can be > metablock size), but I should file a separate issue for it since that's unrelated to this issue.

I'm a bit unsure as to how to go about refactoring your code to deal with this bug.

**Comment by ende76** [comment]
If you can't, I should be able to get to it over the weekend.

I'm not sure I agree with your insert length > metablock size interpretation.

I'm talking specifically about this part:
>             if number of uncompressed bytes produced in the loop for
>                this meta-block is MLEN, then break from loop (in this
>                case the copy length is ignored and can have any value)

I'm not sure how intricately familiar you are with the spec yet. You might know it very well, since you've found and fixed bugs in the code already. In that case, ignore the explanation. ;)
In the Brotli format, at its simplest, there are two commands: to insert new bytes, and to copy existing bytes from earlier in the stream. These commands get repeated over and over, until the input stream is decoded.
In the encoded stream, those commands are encoded as well, and the two parts (insert and copy) are basically one single entity.
Now, the part of the spec above says, as I understand it, that at the end of a metablock, if the insert command already fills up the metablock (exactly to MLEN bytes), then we can discard the second half of the command pair, i.e. the copy command, and we don't care what value it had for the copy length.

I'm fairly confident that that case is properly handled.

Let me know if I misunderstood the issue you found.

**Comment by danielrh** [comment]
Hmm you're right... The spec is a bit confusingly worded since the statement looked to be in the loop and you could imagine checking after each byte. But yes in all my examples the issue happens when a transformation occurs that truncates the dictionary word as the last item in the metablock.

**Comment by ende76** [comment]
Excellent! Thanks so much for your work, again. I'm planning on fixing the MLEN check on Sunday the latest.

**Comment by danielrh** [comment]
Turns out you already had the checks where they needed to be after the transform--you just had a redundant check before the transforms
Removing that seems to solve the issue!
Also it was easy to repro the issue with a ten byte file
