### ISSUE TITLE
Uncompressed data is not fed into the literal_buf

### ISSUE THREAD

**Issue by danielrh** [ende76/brotli-rs#23]
Brotli expects the literal_buf to be prepopulated with uncompressed_data, if such data is encountered before something needing context bytes.

Currently the literal_buf is left to be 0,0 despite an uncompressed meta-block being encountered

**Comment by ende76** [comment]
I agree, the literals in that case absolutely must be pushed into literal_buf. I'm amazed both that this bug has existed for a considerable time now, and that you've found it.
Would you mind submitting your fix as a pull request?

**Comment by ende76** [comment]
Nevermind, I saw it's covered in #21.
